---
title: "mp3"
author: "Yejin Hwang, Lisa Chen"
date: "11/16/2017"
output: html_document
---

```{r}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")
dbListTables(db)
```
```{r}
dbListFields(db,"title")
```
```{r}
titles <- dbGetQuery(db, "SELECT * FROM title LIMIT 0,100;")
View(titles)

db %>%
  tbl("title") %>%
  head(3)
```

```{r}
west<- db %>%
  dbGetQuery("SELECT  mi.movie_id, title, production_year
FROM movie_info mi
LEFT JOIN title t ON mi.movie_id = t.id
LEFT JOIN kind_type kt ON kind_id =  kt.id
WHERE info_type_id = 3 AND info = 'Western' AND kind='movie';")
#save(west,file="Westerns.rda")
#load("Westerns.rda")
#ggplot(west,aes(x=production_year, y=))
```

```{r}
#SELECT t.title, t.production_year, series_years, keyword

west2<- db %>%
  dbGetQuery("SELECT mi.info_type_id, mi.info,mi2.info_type_id, mi2.info,mi1x.info_type_id, mi1x.info,mi2x.info_type_id, mi2x.info
FROM title t
JOIN movie_info AS mi ON t.id = mi.movie_id
JOIN movie_info mi2 ON mi2.movie_id=t.id
JOIN movie_keyword mk on t.id = mk.movie_id
JOIN keyword k ON mk.keyword_id
JOIN movie_info_idx AS mi1x ON mi1x.movie_id = t.id
JOIN movie_info_idx AS mi2x ON mi2x.movie_id = t.id
LEFT JOIN kind_type kt ON kind_id =  kt.id
WHERE mi.info_type_id = 3 AND mi.info='Western' 
AND mi2.info_type_id=4 AND mi2.info='English'
AND kind='movie'
AND t.kind_id = 1
  AND mi1x.info_type_id = 100
  AND mi2x.info_type_id = 101
  AND mi1x.info > 100000
ORDER BY mi2x.info desc;")
```
```{r}
west3<- db %>%
  dbGetQuery("SELECT t.title, t.production_year, series_years, keyword, kind, mi1x.info, mi2x.info, mi3x.info , mi4x.info
FROM title t
JOIN movie_info mi ON t.id = mi.movie_id
JOIN movie_info mi2 ON mi2.movie_id=t.id
JOIN movie_keyword mk ON t.id = mk.movie_id
JOIN keyword k ON k.id=mk.keyword_id
JOIN movie_info_idx AS mi1x ON mi1x.movie_id = t.id
JOIN movie_info_idx AS mi2x ON mi2x.movie_id = t.id
JOIN movie_info_idx AS mi3x ON mi3x.movie_id = t.id
JOIN movie_info_idx AS mi4x ON mi4x.movie_id = t.id
LEFT JOIN kind_type kt ON kind_id =  kt.id
WHERE mi.info_type_id = 3 AND mi.info='Western' 
AND mi2.info_type_id=4 AND mi2.info='English'
AND kind='movie' OR kind='tv movie'
  AND mi1x.info_type_id = 100
  AND mi2x.info_type_id = 101
  AND mi3x.info_type_id = 105
  AND mi4x.info_type_id = 107
  AND mi1x.info > 100000
GROUP BY t.title, t.production_year
ORDER BY mi2x.info desc;")
```
```{r}

# filter out non_movies
movie <- db %>%
  dbGetQuery(" SELECT *
               FROM title
               where kind_id = 1;
             ")
```

```{r}
kindWest <- db %>%
  dbGetQuery("SELECT title, production_year, kind
FROM title t
LEFT JOIN kind_type kt ON kt.id = t.kind_id 
LEFT JOIN movie_info_idx mi1 ON mi1.movie_id = t.id
LEFT JOIN movie_info_idx mi2 ON mi2.movie_id = t.id
LEFT JOIN movie_info mi3 ON mi3.movie_id = t.id
WHERE kind='movie' OR kind='tv movie' 
AND mi1.info_type_id = 3 AND mi1.info = 'Western'
AND mi2.info_type_id = 4 AND mi2.info = 'English';")
save(kindWest,file="kindWest.rda")
load("kindWest.rda")
```
```{r}
filtered1 <- db %>%
  dbGetQuery("SELECT title, production_year, kind
FROM title t
LEFT JOIN kind_type kt ON kt.id = t.kind_id 
LEFT JOIN movie_info_idx mi2 ON mi2.movie_id = t.id
LEFT JOIN movie_info mi3 ON mi3.movie_id = t.id
WHERE kind='movie' OR kind='tv movie' 
AND mi2.info_type_id = 4 AND mi2.info = 'English';")
save(filtered1,file="filtered1.rda")
load("filtered1.rda")
```
```{r}
ggplot(kindWest,aes(x=production_year)) + geom_bar()

```

```{r}
ggplot(kindWest,aes(x=production_year,color = kind)) + geom_bar(position="stack")

```
```{r}

q1 <- db %>%
  dbGetQuery(" SELECT production_year, count(*) as num_films
               FROM title
               WHERE kind_id = 1
               GROUP BY production_year;
             ")
```
```{r}
ggplot(kindWest,aes(x=production_year)) + geom_histogram()

```





```{r}

q2 <- db %>%
  dbGetQuery(" SELECT t.production_year, count(*) as num_westerns
               FROM title t , movie_info mi
               WHERE t.kind_id = 1 and t.id = mi.movie_id and mi.info LIKE '%Westerns%'
               Order BY t.production_year;
             ")
View(q2)
```



```{r}

tbl <- merge(x = q1, y = q2, by = "production_year", all = TRUE)

tbl <- mutate(tbl, percent = num_westerns / num_films)
```



```{r}


library(ggplot2)

ggplot(tbl, aes(x =production_year, y =percent)) + geom_point() +geom_smooth()
# as the graph shows, in the 19th century, the western movie was popular.Especially around 1940. also, the Westerns movies gradually less after 1950.

```
#try push 